name: Node.js Package

on:
  push:
    branches:
      - main
      - next
      - beta
    paths:
      - "src/**/*"
      - "!src/**/*.spec.ts"
      - package.json

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 安装 Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '10.x'
      - name: 获取 yarn 缓存目录地址
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: 安装依赖
        run: yarn --frozen-lockfile
      - name: 运行代码检查
        run: yarn lint
      - name: 运行单元测试
        run: yarn ci
      - name: 上传测试覆盖率报告
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: codecov/codecov-action@v1
        with:
          verbose: true
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: 发布正式版
        if: ${{ github.ref == 'refs/heads/main' }}
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 发布预览版
        if: ${{ github.ref == 'refs/heads/next' }}
        run: yarn publish --tag=next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 发布测试版
        if: ${{ github.ref == 'refs/heads/beta' }}
        run: yarn publish --tag=beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 生成 API 文档
        if: ${{ github.ref == 'refs/heads/main' }}
        run: yarn ts-doc
      - name: 部署文档到 Github Pages 上
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist-tsdoc
