name: Node.js CI

on:
  push:
    branches-ignore:
      - main
      - beta
      - next
    paths:
      - src/**/*
      - api-extractor.json
      - package.json
      - jest.config.js

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 安装 Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '10.x'
      - name: 获取 yarn 缓存目录地址
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: 安装依赖
        run: yarn --frozen-lockfile
      - name: 运行代码检查
        run: yarn lint
      - name: 运行单元测试
        run: yarn ci
      - name: 检查 API 导出情况
        run: |
          yarn build
          yarn ts-check
