name: Node.js CI

on:
  push:
    branches-ignore:
      - main
      - beta
      - next
    paths:
      - src/**/*
      - api-extractor.json
      - package.json
      - jest.config.js

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 10.x
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run lint
        run: yarn lint
      - name: Run tests
        run: yarn ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          verbose: true
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

