name: Node.js CI

on:
  push:
    branches:
      - main
      - next
    paths:
      - src/**/*
      - api-extractor.json
      - package.json
      - jest.config.js
  pull_request:
    branches:
      - main
      - dev
      - 'feat/**'
      - 'releases/**'
    paths:
      - src/**/*
      - api-extractor.json
      - jest.config.js
      - package.json

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 10.x
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run lint
        run: yarn lint
      - name: Run tests
        run: yarn ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          verbose: true
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

